version: '3.8'
services:
  volopa-api:
    container_name: volopa-api
    build:
      context: .
      dockerfile: ./volopa-api/docker/Dockerfile
      args:
        - NODE_VERSION=14.x
    ports:
      - "48080:80"
      - "39443:443"
    env_file:
      - ./volopa-api/.env
    networks:
        - volopa

  volopa-db:
      container_name: volopa-db
      image: mysql:8.0.30
      restart: always
      ports:
          - "43306:3306"
      env_file:
          - ./volopa-api/.env
      networks:
          - volopa

  volopa-app:
    container_name: volopa-app
    build:
      context: .
      dockerfile: ./volopa-app/docker/Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './volopa-app/docker/nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - volopa

  volopa-prod:
    container_name: volopa-prod
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - './proxy/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - volopa
volumes:
  volopa-db: null
  volopa-app: null
  volopa-prod: null

networks:
  volopa:
    name: volopa
    driver: bridge
